# Generated by Django 2.0.4 on 2018-04-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='footage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='price_for_1m',
            field=models.FloatField(),
        ),
    ]
