# Generated by Django 2.0.4 on 2018-04-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_auto_20180412_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_model', models.CharField(max_length=50)),
                ('sewing_cost', models.FloatField()),
                ('sewing_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='material',
            old_name='title',
            new_name='title_material',
        ),
    ]
