# Generated by Django 2.0.4 on 2018-04-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_auto_20180412_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='sewing_time',
            field=models.TimeField(),
        ),
    ]
