# Generated by Django 2.0.4 on 2018-04-11 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_auto_20180412_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Color')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Material')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Model')),
            ],
        ),
    ]
