# Generated by Django 2.0.4 on 2018-04-11 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_catalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('date_of_completion', models.DateTimeField()),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studio.Catalog')),
            ],
        ),
    ]
